### ISSUE TITLE
Predicate judgment doesn't return result of final switch expression

### ISSUE THREAD

**Issue by lwrage** [LorenzoBettini/xsemantics#73]
The predicate judgment below does not behave as I had expected. It always returns `true` instead of the result of the switch. It works if I assign the result of the switch to a variable and return the value of this variable as in the comment lines.

```
rule CompareNumbers
    G |> NumberValue left : NumberValue right
from {
    G |> left : right ~> var Integer cmp
    val op = env(G, 'op', Operation)
    // val b =
    switch (op) {
        case LT: cmp < 0        
        case LEQ: cmp <= 0
        case GT: cmp > 0
        case GEQ: cmp >= 0
        default: false // to eliminate warning
    }
    // b
}
```

The code generator doesn't treat the switch as an expression and doesn't calculate a result for it. Here's the generated code:

```
  protected Result<Boolean> applyRuleCompareNumbers(final RuleEnvironment G, final RuleApplicationTrace _trace_, final NumberValue left, final NumberValue right) throws RuleFailedException {
    /* G |> left : right ~> var Integer cmp */
    Integer cmp = null;
    Result<Integer> result = cmpNumInternal(G, _trace_, left, right);
    checkAssignableTo(result.getFirst(), Integer.class);
    cmp = (Integer) result.getFirst();

    final Operation op = this.<Operation>env(G, "op", Operation.class);
    if (op != null) {
      switch (op) {
        case LT:
          /* ((cmp).intValue() < 0); */
          break;
        case LEQ:
          /* ((cmp).intValue() <= 0); */
          break;
        case GT:
          /* ((cmp).intValue() > 0); */
          break;
        case GEQ:
          /* ((cmp).intValue() >= 0); */
          break;
        default:
          /* false */
          break;
      }
    } else {
      /* false */
    }
    return new Result<Boolean>(true);
  }
```

**Comment by LorenzoBettini** [comment]
@lwrage I checked the behavior and this is actually the expected one as documented here: http://xsemantics.sourceforge.net/xsemantics-documentation/XsemanticsSyntax.html#ExpressionsInPremises

You need to enclose the boolean expression in a block, if you want it to be treated as a boolean premise (assertion), in fact, boolean expressions are considered as assertions only when they are part of a block.

It might sound confusing, but I had to come up with a strategy that gives the declarative boolean assertion style without breaking too much the procedural style of the expression language.

I mean, if you want to use boolean assertions you should really use the declarative style, e.g.,

```
{
  op == LT
  cmp < 0
}
or
{
  op == LEQ
  cmp <= 0
}
```

if you use the switch statement (not declarative style), then you should use it completely. 
For example, "assign the result of the switch to a variable and ASSERT the value of this variable" would be the preferred solution, if you want to use a switch. Note that I'm saying "assert" and not "return" because a judgment does NOT return anything: you assign the result to the output parameter if the judgment has output parameters. If the judgment has no output parameter then it can be seen as a predicate: if succeeds if no assertion fails (but there's no explicit return).

As I said, if you do something like that

```
case LT: { cmp < 0 }
``` 

would work as well, but I wouldn't do that.

Please let me know if you have other questions.

**Comment by lwrage** [comment]
I had assumed that the switch expression _as a whole_ would count as the Boolean expression which is used as a statement. The examples given show that it is not the case.\
However, it is still not quite clear to me for which subset of Xbase expressions I don't need the curly braces.

**Comment by lwrage** [comment]
I see. Unfortunately the Xbase documentation seems rather vague.w.r.t., type inference.
